# Generated by Django 4.2 on 2023-10-19 12:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Author', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('Price', models.IntegerField(default=0)),
                ('Genre', models.IntegerField(choices=[('Romantic', 1), ('Fantasy', 2), ('Historical', 3), ('Political', 4), ('Biography', 5), ('Motivational', 6), ('HolyDefense', 7), ('Literature', 8), ('Business', 9), ('TuitionAssistance', 10), ('KidsAndTeenager', 11), ('Poetry', 12)], default=0)),
                ('Publisher', models.CharField(max_length=100)),
                ('nPage', models.IntegerField(default=0)),
                ('PrintYear', models.IntegerField(default=1402)),
                ('ISBN', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=11)),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('NationalCode', models.CharField(blank=True, max_length=10)),
                ('Birthday', django_jalali.db.models.jDateField(blank=True)),
                ('Character', models.IntegerField(choices=[('User', 1), ('Author', 2)], default=1)),
            ],
        ),
    ]
