# Generated by Django 4.2 on 2023-10-19 13:00

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Character',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Author')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
