# Generated by Django 4.2 on 2023-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_user_birthday_alter_user_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentTime)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=index.models.currentTime),
        ),
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.IntegerField(choices=[(1, 'Romantic'), (2, 'Fantasy'), (3, 'Historical'), (4, 'Political'), (5, 'Biography'), (6, 'Motivational'), (7, 'HolyDefense'), (8, 'Literature'), (9, 'Business'), (10, 'TuitionAssistance'), (11, 'KidsAndTeenager'), (12, 'Poetry')], default=0),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory', models.IntegerField(default=0)),
                ('PricePerCoin', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='index.category'),
        ),
    ]
