# Generated by Django 4.2 on 2023-10-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_category_book_registertime_alter_book_genre_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Category',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.category')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.genre'),
        ),
    ]
