# Generated by Django 4.2 on 2023-10-19 19:07

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_book_category_genre_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApiKey', models.TextField(default=index.models.createSession)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentTime)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Name',
        ),
        migrations.AddField(
            model_name='category',
            name='ArbName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='PerName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='genre',
            name='ArbName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='genre',
            name='PerName',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Session',
            field=models.TextField(default=index.models.createSession),
        ),
        migrations.AlterField(
            model_name='user',
            name='Character',
            field=models.IntegerField(choices=[(1, 'کاربر'), (2, 'نویسنده')], default=1),
        ),
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentTime)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.user')),
            ],
        ),
    ]
