# Generated by Django 4.2 on 2023-10-19 20:22

from django.db import migrations, models
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_apikey_remove_category_name_remove_genre_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=index.models.randomInt)),
                ('Phone', models.CharField(max_length=11)),
                ('isVerify', models.BooleanField(default=False)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentTime)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Language',
            field=models.IntegerField(choices=[('فارسی', 1), ('عربی', 2)], default=1),
        ),
    ]
