# Generated by Django 4.2 on 2023-10-20 03:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_verifycode_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('Expertise', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='developer/default.png', upload_to=index.models.uploadToDeveloper)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentTime)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUs', models.TextField(max_length=2000)),
                ('Contact', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Image',
            field=models.ImageField(default='book/default.png', upload_to=index.models.uploadToBook),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
