# Generated by Django 4.2 on 2023-10-20 04:09

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_developers_infoproject_book_image_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='Name',
            field=models.CharField(default=index.models.randomInt, max_length=100),
        ),
    ]
