# Generated by Django 4.2 on 2023-10-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_apikey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Birthday',
        ),
    ]
