# Generated by Django 4.2 on 2023-10-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Character',
        ),
        migrations.AlterField(
            model_name='user',
            name='Language',
            field=models.IntegerField(choices=[(1, 'فارسی'), (1, 'عربی')], default=1),
        ),
    ]
